### ISSUE TITLE
How can I change the logo of the nav bar.

### ISSUE THREAD

**Issue by shaishguni** [Aleksi44/django-admin-tailwind#1]
I want to change it and replace it can you say how can I. 👍

**Comment by Aleksi44** [comment]
Hi @shaishguni 

This is possible by [overriding Django templates](https://docs.djangoproject.com/en/3.2/howto/overriding-templates/) with these files :

- [admin/base_site.html](https://github.com/Aleksi44/django-admin-tailwind/blob/master/django_admin_tailwind/templates/admin/base_site.html) -> block branding -> logo navbar
- [admin/login.html](https://github.com/Aleksi44/django-admin-tailwind/blob/master/django_admin_tailwind/templates/admin/login.html) -> block branding_login -> logo login

**Comment by shaishguni** [comment]
> Hi @shaishguni
> 
> This is possible by [overriding Django templates](https://docs.djangoproject.com/en/3.2/howto/overriding-templates/) with these files :
> 
> * [admin/base_site.html](https://github.com/Aleksi44/django-admin-tailwind/blob/master/django_admin_tailwind/templates/admin/base_site.html) -> block branding -> logo navbar
> * [admin/login.html](https://github.com/Aleksi44/django-admin-tailwind/blob/master/django_admin_tailwind/templates/admin/login.html) -> block branding_login -> logo login

umm.. ok thanks for the information
