### ISSUE TITLE
Configuring Static files

### ISSUE THREAD

**Issue by mwiks-dev** [Aleksi44/django-admin-tailwind#7]

**Comment by Aleksi44** [comment]
I've just changed the behavior of static files in version `0.0.31`.

Before, the static files were served in an S3 bucket of my own. 
They are now managed from the django app `django_admin_tailwind` in the static folder. 
If you do a collectstatic, you'll have access to these files in the `STATIC_ROOT` folder.

**Comment by mwiks-dev** [comment]
My question is since you are using tailwind static files how are you configuring your own static files for the project

**Comment by Aleksi44** [comment]
For my projects, I use the default configuration for managing my static files in Django described here :

https://docs.djangoproject.com/en/4.2/howto/static-files/

Do you have a bug with this?

**Comment by mwiks-dev** [comment]
Thank you
